# 코드래빗 코드 리뷰 설정
# 참고: https://docs.coderabbit.ai/reference/yaml-template#complete-template

language: ko-KR

early_access: false
enable_free_tier: true

reviews:
  # 코드 리뷰 엄격성 설정. 엄격한 코드 리뷰를 위해서는 assertive 사용
  # 옵션: assertive, chill
  # 기본값: chill
  profile: chill

  # 모든 리뷰 코멘트가 해결되고, pre-merge 체크에 오류가 없을 때 자동으로 승인 처리
  request_changes_workflow: true

  # PR 설명에 변경 사항 요약문 자동 생성
  high_level_summary: true
  # 요약문이 삽입될 위치를 지정하는 텍스트
  high_level_summary_placeholder: '@coderabbitai 요약'
  # 생성된 요약문을 리뷰 코멘트(walkthrough)에도 표시할지 여부
  high_level_summary_in_walkthrough: false

  # PR 제목에 "@coderabbitai 제목" 이 들어있으면 CodeRabbit이 자동으로 제목을 생성
  auto_title_placeholder: '@coderabbitai 제목'
  # PR 제목 생성 지침
  auto_title_instructions: >
    PR 제목은 한국어로 작성합니다.
    제목은 짧고 명확하게, [대상] + [액션] 형식으로 작성합니다.
    제목은 간결하고 설명적이어야 하고, 50자를 넘지 않아야 합니다.
    불필요한 접두사나 티켓 번호를 포함하지 않습니다.

  # 코드 시퀀스 다이어그램을 추가하지 않음
  sequence_diagrams: false

  # 코드 리뷰 난이도 추정 기능 비활성화
  estimate_code_review_effort: false

  # 적절한 라벨을 추천하도록 함
  suggested_labels: true
  # 추천한 라벨을 자동으로 적용하지는 않음
  auto_apply_labels: false

  # 적절한 리뷰어를 추천하지 않음
  suggested_reviewers: false
  # 추천한 리뷰어를 자동으로 할당하지는 않음
  auto_assign_reviewers: false

  # 라벨링 지침
  # 빈 배열의 경우 과거 기록을 참고해서 추천
  labeling_instructions: []

  auto_review:
    # draft PR은 리뷰하지 않음
    drafts: false
    # 자동 리뷰를 적용할 브랜치를 지정
    # 빈 배열인 경우 기본 브랜치를 사용
    base_branches: []

  finishing_touches:
    # Docstring을 자동으로 생성하지 않도록 함
    docstrings:
      enabled: false
    # 코드 변경에 맞는 단위 테스트 코드를 제안하도록 함
    unit_tests:
      enabled: true

  # PR 머지 전 체크사항 설정
  # 옵션: off(검사 안 함), warning(경고만), error(머지 차단)
  pre_merge_checks:
    # Docstring 체크 비활성화
    docstrings:
      mode: off
    # PR 제목 체크 비활성화
    title:
      mode: off
    # PR 설명이 적절한지 체크
    description:
      mode: warning
    # PR이 연결된 이슈를 잘 해결했는지 체크
    issue_assessment:
      mode: warning

chat:
  # @coderabbit 으로 직접 멘션해야 응답
  auto_reply: false
  integrations:
    # Jira 연동 활성화
    jira:
      usage: enabled
    # Linear 연동 비활성화
    linear:
      usage: disabled

# 지식 베이스 설정
knowledge_base:
  # 현재 레포의 데이터만 사용
  learnings:
    scope: local
  # Linear 연동 비활성화
  linear:
    usage: disabled
  # 현재 레포의 PR 데이터만 사용
  pull_requests:
    scope: local

code_generation:
  # 자동 생성되는 Docstring을 한국어로 설정
  docstrings:
    language: ko-KR
