const atomicTypographyReferenceTokens = {
  fontFamily: { base: 'Pretendard' },
  fontWeight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
  fontSize: { 11: 11, 12: 12, 13: 13, 14: 14, 16: 16, 18: 18, 20: 20, 24: 24 },
  lineHeight: {
    0: '150%',
    1: '150%',
    2: '150%',
    3: '150%',
    4: '150%',
    5: '150%',
    6: '150%',
    7: '150%',
    8: '150%',
    9: '140%',
    10: '140%',
    11: '140%',
  },
  letterSpacing: { 0: '0%' },
  paragraphSpacing: { 0: 0 },
  paragraphIndent: { 0: '0px' },
  textCase: { none: 'none' },
  textDecoration: { none: 'none' },
} as const;

const {
  fontFamily,
  fontWeight,
  fontSize,
  lineHeight,
  letterSpacing,
  paragraphSpacing,
  paragraphIndent,
  textCase,
  textDecoration,
} = atomicTypographyReferenceTokens;

const atomicTypographyTokens = {
  'heading.medium': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.bold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[24],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'heading.small': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.bold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[20],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'title.medium': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.semibold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[20],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'title.small': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.semibold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[18],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'body.medium': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.regular,
    lineHeight: lineHeight[0],
    fontSize: fontSize[16],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'body.small': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.regular,
    lineHeight: lineHeight[0],
    fontSize: fontSize[14],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'body.medium-semibold': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.semibold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[16],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'body.small-medium': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.medium,
    lineHeight: lineHeight[0],
    fontSize: fontSize[14],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'body.small-semibold': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.semibold,
    lineHeight: lineHeight[0],
    fontSize: fontSize[14],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'caption.small': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.regular,
    lineHeight: lineHeight[9],
    fontSize: fontSize[13],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'caption.small-medium': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.medium,
    lineHeight: lineHeight[9],
    fontSize: fontSize[13],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
  'caption.xsmall': {
    fontFamily: fontFamily.base,
    fontWeight: fontWeight.regular,
    lineHeight: lineHeight[9],
    fontSize: fontSize[12],
    letterSpacing: letterSpacing[0],
    paragraphSpacing: paragraphSpacing[0],
    paragraphIndent: paragraphIndent[0],
    textCase: textCase.none,
    textDecoration: textDecoration.none,
  },
} as const;

type AtomicTypographyKey = keyof typeof atomicTypographyTokens;

export { atomicTypographyReferenceTokens, atomicTypographyTokens };
export type { AtomicTypographyKey };
