const BANK_LIST: { bankName: string; url: string }[] = [
  { bankName: '경남', url: '/pngs/banks/bankName=경남.png' },
  { bankName: '광주', url: '/pngs/banks/bankName=광주.png' },
  { bankName: '대구', url: '/pngs/banks/bankName=대구.png' },
  { bankName: '부산', url: '/pngs/banks/bankName=부산.png' },
  { bankName: '산림조합', url: '/pngs/banks/bankName=산림조합.png' },
  { bankName: '새마을', url: '/pngs/banks/bankName=새마을.png' },
  { bankName: '수협', url: '/pngs/banks/bankName=수협.png' },
  { bankName: '신한', url: '/pngs/banks/bankName=신한.png' },
  { bankName: '신협', url: '/pngs/banks/bankName=신협.png' },
  { bankName: '씨티', url: '/pngs/banks/bankName=씨티.png' },
  { bankName: '우리', url: '/pngs/banks/bankName=우리.png' },
  { bankName: '우체국', url: '/pngs/banks/bankName=우체국.png' },
  { bankName: '저축은행', url: '/pngs/banks/bankName=저축은행.png' },
  { bankName: '전북', url: '/pngs/banks/bankName=전북.png' },
  { bankName: '제주', url: '/pngs/banks/bankName=제주.png' },
  { bankName: '카카오뱅크', url: '/pngs/banks/bankName=카카오뱅크.png' },
  { bankName: '케이뱅크', url: '/pngs/banks/bankName=케이뱅크.png' },
  { bankName: '토스뱅크', url: '/pngs/banks/bankName=토스뱅크.png' },
  { bankName: '하나', url: '/pngs/banks/bankName=하나.png' },
  { bankName: '한국투자증권', url: '/pngs/banks/bankName=한국투자증권.png' },
  { bankName: 'IBK기업', url: '/pngs/banks/bankName=IBK기업.png' },
  { bankName: 'KB국민', url: '/pngs/banks/bankName=KB국민.png' },
  { bankName: 'KB증권', url: '/pngs/banks/bankName=KB증권.png' },
  { bankName: 'KDB산업', url: '/pngs/banks/bankName=KDB산업.png' },
  { bankName: 'KEB외환', url: '/pngs/banks/bankName=KEB외환.png' },
  { bankName: 'NH농협', url: '/pngs/banks/bankName=NH농협.png' },
  { bankName: 'NH투자증권', url: '/pngs/banks/bankName=NH투자증권.png' },
  { bankName: 'SBI저축', url: '/pngs/banks/bankName=SBI저축.png' },
  { bankName: 'SC제일', url: '/pngs/banks/bankName=SC제일.png' },
];

export default BANK_LIST;
