# 개발서버 CI 워크플로우
name: Dev CI

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        # 락파일을 엄격하게 지키며 설치
        env:
          HUSKY: 0 # CI 환경에서는 git 훅이 불필요하므로 husky 비활성화
        run: yarn install --frozen-lockfile

      - name: Check Prettier
        run: yarn prettier:check

      - name: Check Lint
        run: yarn lint

      - name: Run Unit Test
        run: yarn test

      - name: Build
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_KAKAO_JAVASCRIPT_KEY: ${{ secrets.VITE_KAKAO_JAVASCRIPT_KEY }}
          VITE_SUPABASE_PUBLIC_KEY: ${{ secrets.VITE_SUPABASE_PUBLIC_KEY }}
        run: yarn build
