name: Publish Storybook
# https://www.chromatic.com/docs/github-actions/

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Storybook URL을 코멘트할 PR 번호'
        required: false
        type: number
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths:
      - '**/stories/**'
      - '**/*.stories.tsx'
      - '**/*.stories.ts'

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4 # https://github.com/actions/checkout
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Github Actions에서 사용하는 기본 토큰
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install # 명시적으로 의존성 설치

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run Chromatic
        uses: chromaui/action@latest
        id: chromatic
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # Only run Chromatic on changed stories

      - name: Comment on PR (with snapshot changes)
        if: steps.chromatic.outputs.changeCount != '0' && (github.event_name == 'pull_request' || inputs.pr_number)
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ github.event.pull_request.number || inputs.pr_number }}
          comment-tag: chromatic-storybook
          message: |
            ✨ Storybook
            👉 ${{ steps.chromatic.outputs.storybookUrl }}

            📸 변경된 스냅샷
            👉 ${{ steps.chromatic.outputs.buildUrl }}

      - name: Comment on PR (no snapshot changes)
x        if: steps.chromatic.outputs.changeCount == '0' && (github.event_name == 'pull_request' || inputs.pr_number)
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ github.event.pull_request.number || inputs.pr_number }}
          comment-tag: chromatic-storybook
          message: |
            ✨ Storybook
            👉 ${{ steps.chromatic.outputs.storybookUrl }}

            ✅ 스냅샷 변경 없음
